/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.mReportStok;

/**
 *
 * @author Dell
 */
public class ReportStok extends javax.swing.JPanel {

    /**
     * Creates new form ReportStock
     */
    public DefaultTableModel dtm;
    mReportStok mrs = new mReportStok();

    public ReportStok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_stok = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cb_jenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cb_produk = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        cetak = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Report - Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tb_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_stok);

        jLabel2.setText("Jenis Stok");

        cb_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Mutasi Stok", "Data Stok" }));
        cb_jenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_jenisItemStateChanged(evt);
            }
        });

        jLabel3.setText("Produk");

        cb_produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cb_produk.setEnabled(false);

        jLabel4.setText("Tanggal Awal");

        startDate.setDateFormatString("dd-MM-yyyy");
        startDate.setEnabled(false);

        jLabel5.setText("Tanggal Akhir");

        endDate.setDateFormatString("dd-MM-yyyy");
        endDate.setEnabled(false);

        submit.setText("Proses");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cetak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cb_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cetak))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cb_jenis)
                    .addComponent(cb_produk)
                    .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_jenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_jenisItemStateChanged
        if (cb_jenis.getSelectedItem().equals("Mutasi Stok")) {
            mrs.fun_Clear(this);
            try {
                mrs.fun_GetProduk(this);
                cb_produk.setEnabled(true);
                startDate.setEnabled(true);
                endDate.setEnabled(true);
                submit.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (cb_jenis.getSelectedItem().equals("Data Stok")) {
            mrs.fun_Clear(this);
            try {
                mrs.fun_GetProduk(this);
                cb_produk.setEnabled(false);
                startDate.setEnabled(false);
                endDate.setEnabled(false);
                submit.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (cb_jenis.getSelectedItem().equals("Pilih")) {
            mrs.fun_Clear(this);
            cb_produk.setSelectedItem("Pilih");
            cb_produk.setEnabled(false);
            startDate.setEnabled(false);
            endDate.setEnabled(false);
            submit.setEnabled(false);
        }
    }//GEN-LAST:event_cb_jenisItemStateChanged

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String start = ((JTextField) startDate.getDateEditor().getUiComponent()).getText();
        String end = ((JTextField) endDate.getDateEditor().getUiComponent()).getText();
        if (!cb_jenis.getSelectedItem().equals("Pilih")) {
            if (cb_jenis.getSelectedItem().equals("Mutasi Stok")) {
                if (cb_produk.getSelectedItem().equals("Semua")) {
                    if (!start.isEmpty() && !end.isEmpty()) {
                        try {
                            mrs.fun_TarikAll(this);
                        } catch (SQLException ex) {
                            Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Field Tanggal Awal dan Akhir Kosong!", "Gagal", HEIGHT, mrs.invalid);
                    }
                } else {
                    try {
                        mrs.fun_TarikProduk(this);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else if (cb_jenis.getSelectedItem().equals("Data Stok")) {
                try {
                    mrs.fun_TarikStok(this);
                } catch (SQLException ex) {
                    Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Field Tanggal Awal dan Akhir Kosong!", "Gagal", HEIGHT, mrs.invalid);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        String start = ((JTextField) startDate.getDateEditor().getUiComponent()).getText();
        String end = ((JTextField) endDate.getDateEditor().getUiComponent()).getText();

        if (!cb_jenis.getSelectedItem().equals("Pilih")) {
            if (cb_jenis.getSelectedItem().equals("Mutasi Stok")) {
                if (!start.isEmpty() && !end.isEmpty()) {
                    if (cb_produk.getSelectedItem().equals("Semua")) {
                        try {
                            mrs.fun_cetakAll(this);
                        } catch (SQLException ex) {
                            Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        try {
                            mrs.fun_cetakProduk(this);
                        } catch (SQLException ex) {
                            Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Field Tanggal Awal dan Akhir Kosong!", "Gagal", HEIGHT, mrs.invalid);
                }
            } else if (cb_jenis.getSelectedItem().equals("Data Stok")) {
                try {
                    mrs.fun_cetakStok(this);
                } catch (SQLException ex) {
                    Logger.getLogger(ReportStok.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Field Jenis Kosong!", "Gagal", HEIGHT, mrs.invalid);
        }


    }//GEN-LAST:event_cetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cb_jenis;
    public javax.swing.JComboBox<String> cb_produk;
    private javax.swing.JButton cetak;
    public com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public com.toedter.calendar.JDateChooser startDate;
    public javax.swing.JButton submit;
    public javax.swing.JTable tb_stok;
    // End of variables declaration//GEN-END:variables
}
