/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import static java.util.Collections.replaceAll;
import model.mTransPenjualan;
import popup.PopCariBarang;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFormattedTextField;
import javax.swing.Timer;
import javax.swing.text.NumberFormatter;
import org.apache.poi.xslf.usermodel.Placeholder;

/**
 *
 * @author Dell
 */
public class TransaksiPenjualan extends javax.swing.JPanel {

    public DefaultTableModel tblmodel;

    public DefaultTableModel tablemodelProduk;
    mTransPenjualan pm = new mTransPenjualan();
    double nilai;
    String convert_total = "";
    ImageIcon sucess = new ImageIcon(getClass().getResource("/asset/checked.png"));
    ImageIcon invalid = new ImageIcon(getClass().getResource("/asset/cancel.png"));
    ImageIcon warning = new ImageIcon(getClass().getResource("/asset/warning.png"));
    ImageIcon trash = new ImageIcon(getClass().getResource("/asset/trash.png"));
    public String harga_total = "";
    public String kembalian = "";
    public String nominal_bayar = "";
    public String exBarcode, exNama, exHarga;
    private JFormattedTextField formattedTextField;

    public TransaksiPenjualan() throws SQLException {
        initComponents();
        pm.objectTable(this);
        panel_kredit.setVisible(false);
        pm.fun_GenID(this);
//        pm.fun_GetSales(this);

    }

    public void run() {
        try {
            pm.fun_GetKredit(TransaksiPenjualan.this);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void itemTerpilihBarang() throws SQLException {
        PopCariBarang pcb = new PopCariBarang();
        pcb.tp = this;
        tf_barcode.setText(exBarcode);
        tf_nama.setText(exNama);
        String S1_angka_normal = String.valueOf(exHarga);
        double D1_angka_Normal = Double.parseDouble(S1_angka_normal);
        DecimalFormat DF2 = new DecimalFormat("#,###,##0");
        tf_harga.setText(DF2.format(D1_angka_Normal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_idTrans = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_tipe = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nominal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txt_dibayarkan = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JLabel();
        bt_batal = new javax.swing.JButton();
        bt_selesai = new javax.swing.JButton();
        panel_kredit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_nomor = new javax.swing.JTextField();
        cb_kartu = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_totalharga = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_penjualan = new javax.swing.JTable();
        tf_barcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        min = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_item = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_qty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bt_cari = new javax.swing.JButton();
        cb_sales = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pembeli = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaksi - Penjualan");

        tf_idTrans.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_idTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_idTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total Harga");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Metode Pembayaran");

        cb_tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Tunai", "Transfer", "Kredit", "Digital" }));
        cb_tipe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipeItemStateChanged(evt);
            }
        });
        cb_tipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_tipeFocusLost(evt);
            }
        });
        cb_tipe.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cb_tipeCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cb_tipe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_tipePropertyChange(evt);
            }
        });

        jLabel10.setText("Tipe Pembayaran");

        jLabel11.setText("Nominal Bayar");

        tf_nominal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_nominal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nominal.setEnabled(false);
        tf_nominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nominalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nominalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nominalKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Dibayarkan");

        txt_dibayarkan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_dibayarkan.setText("0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Kembali");

        txt_kembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_kembali.setText("0");

        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_selesai.setText("Selesai");
        bt_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selesaiActionPerformed(evt);
            }
        });

        panel_kredit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Nomor / Nama Kartu");

        tf_nomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nomorKeyReleased(evt);
            }
        });

        cb_kartu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cb_kartu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_kartuMouseClicked(evt);
            }
        });

        jLabel20.setText("Nomor Kartu");

        javax.swing.GroupLayout panel_kreditLayout = new javax.swing.GroupLayout(panel_kredit);
        panel_kredit.setLayout(panel_kreditLayout);
        panel_kreditLayout.setHorizontalGroup(
            panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cb_kartu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tf_nomor, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_kreditLayout.createSequentialGroup()
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_kreditLayout.setVerticalGroup(
            panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kreditLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_kartu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rp. ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Rp. ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setText("Rp.");

        txt_totalharga.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_totalharga.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalharga, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txt_totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel_kredit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_tipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(tf_nominal, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_dibayarkan, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(bt_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_kredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dibayarkan)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kembali)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_penjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_penjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_penjualan);

        tf_barcode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tf_barcodePropertyChange(evt);
            }
        });
        tf_barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_barcodeKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Barcode/Kode Barang");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        min.setBackground(new java.awt.Color(255, 0, 51));
        min.setText("-");
        min.setEnabled(false);
        min.setPreferredSize(new java.awt.Dimension(41, 23));
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });

        jLabel2.setText("Jumlah Item :");

        txt_item.setText("0");

        jLabel5.setText("Jumlah Qty : ");

        txt_qty.setText("0");

        tf_nama.setEnabled(false);

        tf_qty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_qtyMouseClicked(evt);
            }
        });
        tf_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_qtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_qtyKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Qty");

        tf_harga.setForeground(new java.awt.Color(204, 204, 204));
        tf_harga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_hargaFocusLost(evt);
            }
        });
        tf_harga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_hargaMouseClicked(evt);
            }
        });
        tf_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_hargaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_hargaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_hargaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Harga");

        bt_cari.setBackground(new java.awt.Color(153, 153, 153));
        bt_cari.setText("Cari");
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        cb_sales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cb_sales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_salesItemStateChanged(evt);
            }
        });
        cb_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_salesMouseClicked(evt);
            }
        });
        cb_sales.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_salesPropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Salesman");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Pembeli / Nama Toko");

        pembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pembeliKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_item)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_qty))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(cb_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cari)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pembeli)
                                    .addComponent(tf_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_sales, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(pembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_harga)
                    .addComponent(tf_qty)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nama)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_item)
                    .addComponent(jLabel5)
                    .addComponent(txt_qty))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_barcodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tf_barcodePropertyChange

    }//GEN-LAST:event_tf_barcodePropertyChange

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        pm.fun_Delete(this);
    }//GEN-LAST:event_minActionPerformed

    private void tf_barcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_barcodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                pm.fun_Cari(this);
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }
    }//GEN-LAST:event_tf_barcodeKeyPressed

    private void tf_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int input = Integer.parseInt(tf_qty.getText());
            if (input < 1) {
                JOptionPane.showMessageDialog(null, "Qty Belum Terisi!", "Perhatian!", HEIGHT, warning);
            } else {
                if (tf_harga.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Harga Jual Kosong!", "Perhatian!", HEIGHT, warning);
                    tf_harga.requestFocus();
                } else {
                    try {
                        pm.fun_CekStok(this);
                    } catch (SQLException ex) {
                        Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        } else {

        }
    }//GEN-LAST:event_tf_qtyKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            pm.fun_CekStok(this);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_tipeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipeItemStateChanged
//        persentase();
        if (evt.getItem().equals("Transfer")) {
            run();
            panel_kredit.setVisible(true);
            tf_nominal.setEnabled(true);
            tf_nomor.setText("");
        } else if (evt.getItem().equals("Kredit")) {
            run();
            panel_kredit.setVisible(true);
            tf_nominal.setEnabled(true);
            tf_nomor.setText("");
        } else if (evt.getItem().equals("Digital")) {
            run();
            panel_kredit.setVisible(true);
            tf_nominal.setEnabled(true);
            tf_nomor.setText("");
        } else if (evt.getItem().equals("Tunai")) {
            tf_nominal.setEnabled(true);
            panel_kredit.setVisible(false);
            tf_nomor.setText("-");
            cb_kartu.setSelectedItem("-");
        } else {
            panel_kredit.setVisible(false);
            tf_nominal.setEnabled(false);
        }
    }//GEN-LAST:event_cb_tipeItemStateChanged

    private void tf_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hargaKeyReleased
        String har = tf_harga.getText().replaceAll("\\,", "");
        double harga = Double.parseDouble(har);
        DecimalFormat df = new DecimalFormat("#,###,##0");
        if (harga > 999) {
            tf_harga.setText(df.format(harga));
        }
    }//GEN-LAST:event_tf_hargaKeyReleased

    private void tf_nominalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nominalKeyTyped
        FilterAngka(evt);
    }//GEN-LAST:event_tf_nominalKeyTyped

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        PopCariBarang pcb = new PopCariBarang();
        pcb.tp = this;
        min.setEnabled(false);
        pcb.setVisible(true);
        pcb.setResizable(false);
    }//GEN-LAST:event_bt_cariActionPerformed

    private void table_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_penjualanMouseClicked
        pm.fun_Ubah(this);
    }//GEN-LAST:event_table_penjualanMouseClicked

    private void tf_nomorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomorKeyReleased
        int position = tf_nomor.getCaretPosition();
        tf_nomor.setText(tf_nomor.getText().toUpperCase());
        tf_nomor.setCaretPosition(position);
    }//GEN-LAST:event_tf_nomorKeyReleased

    private void tf_nominalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nominalKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            if (tf_nominal.getText().length() == 0) {
                txt_dibayarkan.setText("0");
            }
        }
        pm.fun_bayar(this);
    }//GEN-LAST:event_tf_nominalKeyReleased

    private void bt_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_selesaiActionPerformed
        String t = txt_totalharga.getText().replaceAll("\\,", "");
        String n = tf_nominal.getText().replaceAll("\\,", "");
        String k = txt_kembali.getText().replaceAll("\\,", "");

        String pembayaran = cb_tipe.getSelectedItem().toString();
        int bayar = Integer.parseInt(k);
        int row = Integer.parseInt(txt_item.getText());
        String sales = cb_sales.getSelectedItem().toString();

        if (!sales.equals("Pilih") && !pembeli.getText().isEmpty()) {
            if (row > 0) {
                if (!cb_tipe.getSelectedItem().equals("Pilih")) {
                    if (pembayaran.equals("Tunai")) {
                        if (!tf_nominal.getText().isEmpty()) {
                            if (bayar < 0) {
                                JOptionPane.showMessageDialog(null, "Nominal Kurang Dari Total Harga!", "Perhatian!", HEIGHT, warning);
                            } else {
                                harga_total = t;
                                nominal_bayar = n;
                                kembalian = k;
                                try {
                                    pm.fun_Simpan(this);
                                } catch (SQLException ex) {
                                    Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Nominal Kosong!", "Perhatian!", HEIGHT, warning);
                        }
                    } else {
                        if (cb_kartu.getSelectedItem().equals("Pilih") || tf_nomor.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Data Kartu Belum Lengkap!", "Perhatian!", HEIGHT, warning);
                        } else {
                            if (row > 0 && !tf_nominal.getText().isEmpty()) {
                                if (bayar < 0) {
                                    JOptionPane.showMessageDialog(null, "Nominal Kurang Dari Total Harga!", "Perhatian!", HEIGHT, warning);
                                } else {
                                    harga_total = t;
                                    nominal_bayar = n;
                                    kembalian = k;
                                    try {
                                        pm.fun_Simpan(this);
                                    } catch (SQLException ex) {
                                        Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Nominal Kosong!", "Perhatian!", HEIGHT, warning);
                            }

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Tentukan Jenis Pembayaran!", "Perhatian!", HEIGHT, warning);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Belum ada item!", "Perhatian!", HEIGHT, warning);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data Sales atau Pembeli Kosong!", "Perhatian!", HEIGHT, warning);
        }

    }//GEN-LAST:event_bt_selesaiActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Yakin Mau Membatalkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String query = "DELETE FROM mutasi_stok WHERE notrans=? and id=?";
            try {
                int t = table_penjualan.getRowCount();
                for (int i = 0; i < t; i++) {
                    String barcode = table_penjualan.getValueAt(i, 1).toString();
                    PreparedStatement stat2 = koneksi.Server.getConnection().prepareStatement(query);
                    stat2.setString(1, tf_idTrans.getText());
                    stat2.setString(2, barcode);
                    stat2.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Sudah Dibersihkan!", "Berhasil", HEIGHT, trash);
                pm.fun_Clear(this);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ada Sedikit Masalah! " + ex.getMessage(), "Gagal", HEIGHT, invalid);
            }
        }
    }//GEN-LAST:event_bt_batalActionPerformed

    private void cb_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_salesMouseClicked

    }//GEN-LAST:event_cb_salesMouseClicked

    private void cb_salesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_salesItemStateChanged

    }//GEN-LAST:event_cb_salesItemStateChanged

    private void cb_salesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_salesPropertyChange
        try {
            pm.fun_GetSales(this);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_salesPropertyChange

    private void tf_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qtyKeyTyped
        FilterAngka(evt);
    }//GEN-LAST:event_tf_qtyKeyTyped

    private void tf_hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hargaKeyTyped
        FilterAngka(evt);
    }//GEN-LAST:event_tf_hargaKeyTyped

    private void tf_hargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_hargaMouseClicked
        tf_harga.setText("");
        tf_harga.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_tf_hargaMouseClicked

    private void tf_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hargaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_qty.requestFocus();
        }
    }//GEN-LAST:event_tf_hargaKeyPressed

    private void tf_nominalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nominalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nominalKeyPressed

    private void tf_qtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_qtyMouseClicked

    }//GEN-LAST:event_tf_qtyMouseClicked

    private void tf_hargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_hargaFocusLost
        int asli = Integer.parseInt(exHarga);
        int harjual = Integer.parseInt(tf_harga.getText().replaceAll("\\,", ""));

        if (harjual < asli) {
            JOptionPane.showMessageDialog(null, "Harga Jual Kurang Dari Harga Asli!", "Perhatian!", HEIGHT, warning);
            String S1_angka_normal = String.valueOf(exHarga);
            double D1_angka_Normal = Double.parseDouble(S1_angka_normal);
            DecimalFormat DF2 = new DecimalFormat("#,###,##0");
            tf_harga.setText(DF2.format(D1_angka_Normal));
            tf_harga.setForeground(new Color(204, 204, 204));
        } else {
            tf_qty.requestFocus();
        }
    }//GEN-LAST:event_tf_hargaFocusLost

    private void cb_kartuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_kartuMouseClicked

    }//GEN-LAST:event_cb_kartuMouseClicked

    private void cb_tipePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_tipePropertyChange

    }//GEN-LAST:event_cb_tipePropertyChange

    private void cb_tipeCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cb_tipeCaretPositionChanged

    }//GEN-LAST:event_cb_tipeCaretPositionChanged

    private void cb_tipeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_tipeFocusLost

    }//GEN-LAST:event_cb_tipeFocusLost

    private void pembeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pembeliKeyReleased
        int position = pembeli.getCaretPosition();
        pembeli.setText(pembeli.getText().toUpperCase());
        pembeli.setCaretPosition(position);
    }//GEN-LAST:event_pembeliKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_batal;
    public javax.swing.JButton bt_cari;
    public javax.swing.JButton bt_selesai;
    public javax.swing.JComboBox<String> cb_kartu;
    public javax.swing.JComboBox<String> cb_sales;
    public javax.swing.JComboBox<String> cb_tipe;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton min;
    private javax.swing.JPanel panel_kredit;
    public javax.swing.JTextField pembeli;
    public javax.swing.JTable table_penjualan;
    public javax.swing.JTextField tf_barcode;
    public javax.swing.JTextField tf_harga;
    public javax.swing.JTextField tf_idTrans;
    public javax.swing.JTextField tf_nama;
    public javax.swing.JTextField tf_nominal;
    public javax.swing.JTextField tf_nomor;
    public javax.swing.JTextField tf_qty;
    public javax.swing.JLabel txt_dibayarkan;
    public javax.swing.JLabel txt_item;
    public javax.swing.JLabel txt_kembali;
    public javax.swing.JLabel txt_qty;
    public javax.swing.JLabel txt_totalharga;
    // End of variables declaration//GEN-END:variables
}
